<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('patrol_schedules', function (Blueprint $table) {
            $table->id();
            $table->date('patrol_date')->index();
            $table->string('officer_name')->nullable()->comment('Filled in by a dispatcher after AI proposes the hotspot slot');
            $table->string('unit_code', 30)->nullable()->comment('Patrol unit / vehicle radio code');
            $table->enum('shift', ['pagi', 'siang', 'malam'])->comment('Morning/Day/Night shift');

            $table->geometry('hotspot_location', subtype: 'point', srid: 4326)
                ->comment('Centroid of the violation/CRM cluster this dispatch targets');
            $table->string('hotspot_label')->comment('Human-readable area name, e.g. "Simpang Blok M - Jalur Busway"');
            $table->unsignedTinyInteger('priority')->default(3)->comment('1 = highest priority');

            $table->unsignedInteger('linked_violation_count')->default(0);
            $table->unsignedInteger('linked_crm_count')->default(0);

            $table->text('ai_rationale')->nullable()->comment('Gemini-generated justification for this dispatch slot');
            $table->enum('status', ['scheduled', 'dispatched', 'completed', 'cancelled'])->default('scheduled')->index();

            $table->foreignId('generated_by')->nullable()->constrained('users')->nullOnDelete()
                ->comment('Null when auto-generated by the daily AI report job');
            $table->timestamps();
        });

        DB::statement('CREATE INDEX patrol_schedules_hotspot_gist ON patrol_schedules USING GIST (hotspot_location)');
    }

    public function down(): void
    {
        Schema::dropIfExists('patrol_schedules');
    }
};
