<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('traffic_violations', function (Blueprint $table) {
            $table->id();
            $table->uuid('event_uuid')->unique()->comment('Idempotency key generated by the edge worker per detection event');

            $table->foreignId('camera_id')->constrained('cctv_cameras')->cascadeOnDelete();

            $table->enum('violation_type', ['illegal_parking', 'busway_lane_intrusion'])->index();
            $table->string('plate_number', 20)->nullable()->index();
            $table->unsignedTinyInteger('plate_confidence')->nullable()->comment('0-100, Groq ANPR confidence score');
            $table->enum('plate_source', ['edge_ocr', 'groq_fallback', 'manual_review'])->default('edge_ocr');

            // PostGIS geometry(Point,4326) -- WGS84 lon/lat, matches GPS/GeoJSON convention.
            $table->geometry('location', subtype: 'point', srid: 4326);

            $table->unsignedInteger('stationary_seconds')->comment('Continuous stopped duration measured by the edge worker');
            $table->unsignedInteger('threshold_seconds')->comment('Threshold configured for this camera/zone at detection time');

            $table->string('frame_path')->comment('Storage disk path to the evidence JPEG frame');
            $table->string('clip_path')->nullable()->comment('Optional short evidence video clip path');

            $table->timestampTz('detected_at')->index();
            $table->enum('status', ['pending_review', 'confirmed', 'dismissed', 'dispatched'])->default('pending_review')->index();
            $table->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestampTz('reviewed_at')->nullable();

            $table->jsonb('meta')->nullable()->comment('Raw YOLO detection payload: bbox, class confidence, track id, frame dims');
            $table->timestamps();
        });

        // GiST index is mandatory for any performant PostGIS spatial query (ST_DWithin, ST_Contains, KNN <->).
        DB::statement('CREATE INDEX traffic_violations_location_gist ON traffic_violations USING GIST (location)');
        DB::statement('CREATE INDEX traffic_violations_detected_at_brin ON traffic_violations USING BRIN (detected_at)');
    }

    public function down(): void
    {
        Schema::dropIfExists('traffic_violations');
    }
};
